src/models/usuario.py
from src.database.db_mysql import db

class Usuario(db.Model):
    __tablename__ = 'usuarios'

    id_usuario = db.Column(db.Integer, primary_key=True)
    id_persona = db.Column(db.Integer, db.ForeignKey('personas.id_persona'), nullable=False)
    rol = db.Column(db.String(25), nullable=False)

    persona = db.relationship('Persona', back_populates='usuario')
    discotecas = db.relationship('Discoteca', back_populates='administrador')

src/routes/__init__.py
from flask import Blueprint, jsonify, render_template
from sqlalchemy import text
from src.database.db_mysql import db
from .auth import auth  # Importa el Blueprint de auth

main = Blueprint('main', __name__)

# Registra el Blueprint de autenticación
main.register_blueprint(auth)


@main.route('/verificar_conexion', methods=['GET'])
def verificar_conexion():
    try:
        db.session.execute(text('SELECT 1'))
        return jsonify({"mensaje": "Conexión a la base de datos exitosa!"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    
@main.route('/test', methods=['GET'])
def test():
    return jsonify({"mensaje": "Ruta de prueba exitosa!"}), 200


# Ruta para la página principal
@main.route('/pagAdmin_principal', methods=['GET'])
def pag_admin_principal():
    return render_template('pagAdmin_principal.html')  # Renderiza el archivo pagAdmin_principal.html

# Ruta para la página principal del Super Admin
@main.route('/pagSuperAdmin_principal', methods=['GET'])
def pag_SuperAdmin_principal():
    return render_template('pagSuperAdmin_principal.html')  # Renderiza el archivo pagAdmin_principal.html

src/routes/admin.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from src.database.db_mysql import db
from sqlalchemy import text
import logging
from datetime import datetime

logging.basicConfig(level=logging.DEBUG)

admin_bp = Blueprint("admin", __name__)

##administradores
@admin_bp.route("/get_all_admin")
def indexAdmin():
    try:
        result = db.session.execute(
            text("""
                SELECT p.id_persona, p.nombre, p.apellido_paterno, p.apellido_materno, 
                    p.dni, p.telefono, p.correo, p.estado FROM personas p
                    inner join usuarios u
                    on p.id_persona = u.id_persona
                    WHERE rol = "administrador";
            """)
        )
        usuarios = result.fetchall()
    except Exception as e:
        flash("Error al obtener los usuarios", "error")
        print(e)
        return redirect(url_for("home.index"))
    finally:
        db.session.close()
    return render_template("usuarios/admin/index.html", usuarios=usuarios)

@admin_bp.route("/add_admin", methods=["GET", "POST"])
def add_admin():
    if request.method == "POST":
        nombre = request.form["nombre"]
        apellido_paterno = request.form["apellido_paterno"]
        apellido_materno = request.form["apellido_materno"]
        dni = request.form["dni"]
        telefono = request.form["telefono"]
        sexo = request.form["sexo"]
        fecha_nacimiento = request.form["fecha_nacimiento"]
        correo = request.form["correo"]
        contrasenia = request.form["contrasenia"]
        estado = True
        fecha_registro = datetime.now()
        rol = "Administrador"

        try:
            result = db.session.execute(
                text("""
                    INSERT INTO personas (nombre, apellido_paterno, apellido_materno, dni, 
                        telefono, sexo, fecha_nacimiento, correo, contrasenia, estado, fecha_registro)
                    VALUES (:nombre, :apellido_paterno, :apellido_materno, :dni, :telefono, :sexo, 
                        :fecha_nacimiento, :correo, :contrasenia, :estado, :fecha_registro)
                """),
                {"nombre": nombre, "apellido_paterno": apellido_paterno, "apellido_materno": apellido_materno, 
                    "dni": dni, "telefono": telefono, "sexo": sexo, "fecha_nacimiento": fecha_nacimiento, 
                    "correo": correo, "contrasenia": contrasenia, "estado": estado, "fecha_registro": fecha_registro}
            )
            id_persona = result.lastrowid
            result = db.session.execute(
                text("""
                    INSERT INTO usuarios (id_persona, rol)
                    VALUES (:id_persona, :rol)
                """),
                {"id_persona": id_persona, "rol": rol}
            )
            db.session.commit()
        except Exception as e:
            flash("Error al agregar el usuario", "error")
            print(e)
            return redirect(url_for("admin.indexAdmin"))
        finally:
            db.session.close()
        flash("Usuario agregado correctamente", "success")
        return redirect(url_for("admin.indexAdmin"))
    return render_template("usuarios/admin/add.html")

@admin_bp.route("/delete_admin/<int:id_persona>")
def deleteAdmin(id_persona):
    try:
        result = db.session.execute(
            text("""
            DELETE FROM usuarios WHERE id_persona = :id_persona;
            """),
            {"id_persona": id_persona}
        )
        result = db.session.execute(
            text("""
            DELETE FROM personas WHERE id_persona = :id_persona;
            """),
            {"id_persona": id_persona}
        )
        db.session.commit()
    except Exception as e:
        flash("Error al eliminar el usuario", "error")
        print(e)
        return redirect(url_for("admin.indexAdmin"))
    finally:
        db.session.close()
    flash("Usuario eliminado correctamente", "success")
    return redirect(url_for("admin.indexAdmin"))

@admin_bp.route("/edit_admin/<int:id_persona>", methods=["GET", "POST"])
def editAdmin(id_persona):
    if request.method == "POST":
        nombre = request.form["nombre"]
        apellido_paterno = request.form["apellido_paterno"]
        apellido_materno = request.form["apellido_materno"]
        dni = request.form["dni"]
        telefono = request.form["telefono"]
        sexo = request.form["sexo"]
        fecha_nacimiento = request.form["fecha_nacimiento"]
        correo = request.form["correo"]
        contrasenia = request.form["contrasenia"]
        estado = request.form["estado"]

        try:
            result = db.session.execute(
                text("""
                    UPDATE personas SET nombre = :nombre, apellido_paterno = :apellido_paterno, 
                    apellido_materno = :apellido_materno, dni = :dni, telefono = :telefono, 
                    sexo = :sexo, fecha_nacimiento = :fecha_nacimiento, correo = :correo, 
                    contrasenia = :contrasenia, estado = :estado WHERE id_persona = :id_persona;
                """),
                {"nombre": nombre, "apellido_paterno": apellido_paterno, "apellido_materno": apellido_materno, 
                    "dni": dni, "telefono": telefono, "sexo": sexo, "fecha_nacimiento": fecha_nacimiento, 
                    "correo": correo, "contrasenia": contrasenia, "estado": estado, "id_persona": id_persona}
            )
            db.session.commit()
        except Exception as e:
            flash("Error al editar el usuario", "error")
            print(e)
            return redirect(url_for("admin.indexAdmin"))
        finally:
            db.session.close()
        flash("Usuario editado correctamente", "success")
        return redirect(url_for("admin.indexAdmin"))
    try:
        result = db.session.execute(
            text("""
                SELECT p.id_persona, p.nombre, p.apellido_paterno, p.apellido_materno, 
                    p.dni, p.telefono, p.sexo, p.fecha_nacimiento, p.estado, p.correo, 
                    p.contrasenia FROM personas p
                    inner join usuarios u
                    on p.id_persona = u.id_persona
                    WHERE p.id_persona = :id_persona;
            """),
            {"id_persona": id_persona}
        )
        usuario = result.fetchone()
    except Exception as e:
        flash("Error al obtener el usuario", "error")
        print(e)
        return redirect(url_for("admin.indexAdmin"))
    finally:
        db.session.close()
    return render_template("usuarios/admin/edit.html", usuario=usuario)

src/templates/usuarios/admin/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Admin</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h2>Crear Administrador</h2>
        <form method="POST" action="{{ url_for('admin.add_admin') }}">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" id="nombre" name="nombre" required>
            </div>
            <div class="form-group">
                <label for="apellido_paterno">Apellido Paterno</label>
                <input type="text" class="form-control" id="apellido_paterno" name="apellido_paterno" required>
            </div>
            <div class="form-group">
                <label for="apellido_materno">Apellido Materno</label>
                <input type="text" class="form-control" id="apellido_materno" name="apellido_materno" required>
            </div>
            <div class="form-group">
                <label for="dni">DNI</label>
                <input type="text" class="form-control" id="dni" name="dni" required>
            </div>
            <div class="form-group">
                <label for="telefono">Teléfono</label>
                <input type="text" class="form-control" id="telefono" name="telefono" required>
            </div>
            <div class="form-group">
                <label for="sexo">Sexo</label>
                <select class="form-control" id="sexo" name="sexo" required>
                    <option value="masculino">Masculino</option>
                    <option value="femenino">Femenino</option>
                </select>
            </div>
            <div class="form-group">
                <label for="fecha_nacimiento">Fecha de Nacimiento</label>
                <input type="date" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" required>
            </div>
            <div class="form-group">
                <label for="correo">Correo</label>
                <input type="email" class="form-control" id="correo" name="correo" required>
            </div>
            <div class="form-group">
                <label for="contrasenia">Contraseña</label>
                <input type="password" class="form-control" id="contrasenia" name="contrasenia" required>
            </div>
            <button type="submit" class="btn btn-primary">Agregar</button>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

src/templates/usuarios/admin/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Administrador</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Editar Administrador</h1>
        <form method="POST">
            <div class="form-group">
                <label for="nombre">Nombre:</label>
                <input type="text" class="form-control" id="nombre" name="nombre" value="{{ usuario.nombre }}" required>
            </div>
            <div class="form-group">
                <label for="apellido_paterno">Apellido Paterno:</label>
                <input type="text" class="form-control" id="apellido_paterno" name="apellido_paterno" value="{{ usuario.apellido_paterno }}" required>
            </div>
            <div class="form-group">
                <label for="apellido_materno">Apellido Materno:</label>
                <input type="text" class="form-control" id="apellido_materno" name="apellido_materno" value="{{ usuario.apellido_materno }}" required>
            </div>
            <div class="form-group">
                <label for="dni">DNI:</label>
                <input type="text" class="form-control" id="dni" name="dni" value="{{ usuario.dni }}" required>
            </div>
            <div class="form-group">
                <label for="telefono">Teléfono:</label>
                <input type="text" class="form-control" id="telefono" name="telefono" value="{{ usuario.telefono }}" required>
            </div>
            <div class="form-group">
                <label for="sexo">Sexo:</label>
                <input type="text" class="form-control" id="sexo" name="sexo" value="{{ usuario.sexo }}" required>
            </div>
            <div class="form-group">
                <label for="fecha_nacimiento">Fecha de Nacimiento:</label>
                <input type="date" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" value="{{ usuario.fecha_nacimiento }}" required>
            </div>
            <div class="form-group">
                <label for="estado">Estado</label>
                <select class="form-control" id="estado" name="estado" required>
                    <option value="1" {{ usuario.estado == 1 and "selected" }}>Activo</option>
                    <option value="0" {{ usuario.estado == 0 and "selected" }}>Inactivo</option>
                </select>
            </div>
            <div class="form-group">
                <label for="correo">Correo:</label>
                <input type="email" class="form-control" id="correo" name="correo" value="{{ usuario.correo }}" required>
            </div>
            <div class="form-group">
                <label for="contrasenia">Contraseña:</label>
                <input type="password" class="form-control" id="contrasenia" name="contrasenia" value="{{ usuario.contrasenia }}" required>
            </div>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

src/templates/usuarios/admin/index.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Users</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .hide-column {
            display: none;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.pag_admin_principal') }}">Discoteca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin.indexAdmin') }}">Administradores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('clientes.indexUser') }}">Clientes</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        <h1 class="mb-4">Administradores</h1>
        <a href="{{ url_for('admin.add_admin') }}" class="btn btn-success mb-3">Crear Nuevo Administrador</a>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th class="hide-column">ID</th>
                    <th>Nombre</th>
                    <th>Apellido Paterno</th>
                    <th>Apellido Materno</th>
                    <th>DNI</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                <tr>
                    <td class="hide-column">{{ usuario.id_persona }}</td>
                    <td>{{ usuario.nombre }}</td>
                    <td>{{ usuario.apellido_paterno }}</td>
                    <td>{{ usuario.apellido_materno }}</td>
                    <td>{{ usuario.dni }}</td>
                    <td>{{ usuario.telefono }}</td>
                    <td>{{ usuario.correo }}</td>
                    <td>{{ usuario.estado == 1 and "Activo" or "Inactivo" }}</td>
                    <td>
                        <a href="{{ url_for('admin.editAdmin', id_persona=usuario.id_persona) }}"
                            class="btn btn-primary btn-sm">Editar</a>
                        <a href="{{ url_for('admin.deleteAdmin', id_persona=usuario.id_persona) }}"
                            class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>