src/routes/__init__.py
from flask import Blueprint, jsonify, render_template
from sqlalchemy import text
from src.database.db_mysql import db
from .auth import auth  # Importa el Blueprint de auth

main = Blueprint('main', __name__)

# Registra el Blueprint de autenticación
main.register_blueprint(auth)


@main.route('/verificar_conexion', methods=['GET'])
def verificar_conexion():
    try:
        db.session.execute(text('SELECT 1'))
        return jsonify({"mensaje": "Conexión a la base de datos exitosa!"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    
@main.route('/test', methods=['GET'])
def test():
    return jsonify({"mensaje": "Ruta de prueba exitosa!"}), 200


# Ruta para la página principal
@main.route('/pagAdmin_principal', methods=['GET'])
def pag_admin_principal():
    return render_template('pagAdmin_principal.html')  # Renderiza el archivo pagAdmin_principal.html

# Ruta para la página principal del Super Admin
@main.route('/pagSuperAdmin_principal', methods=['GET'])
def pag_SuperAdmin_principal():
    return render_template('pagSuperAdmin_principal.html')  # Renderiza el archivo pagAdmin_principal.html

src/routes/categorias.py
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from src.database.db_mysql import db
from sqlalchemy import text

categorias_bp = Blueprint("categorias", __name__)

@categorias_bp.route('/get_all_categorias')
def index():
    try:
        result = db.session.execute(
            text("""
                SELECT * FROM categoria_bebidas
            """)
        )
        categorias = result.fetchall()
    except Exception as e:
        flash('Error al obtener las categorias', 'error')
        return redirect(url_for('home.index'))
    finally:
        db.session.close()
    return render_template('categorias/index.html', categorias=categorias)
    
@categorias_bp.route('/add_categoria', methods=['GET', 'POST'])
def add_categoria():
    if request.method == 'POST':
        nombre = request.form['nombre_categoria']
        descripcion = request.form['descripcion_categoria']
        
        try:
            result = db.session.execute(
                text("""
                    INSERT INTO categoria_bebidas (nombre_categoria, descripcion)
                    VALUES (:nombre, :descripcion);
                """), 
                {'nombre': nombre, 'descripcion': descripcion}
            )
            db.session.commit()
        except Exception as e:
            flash('Error al agregar la categoria', 'error')
            return redirect(url_for('categorias.index'))
        finally:
            db.session.close()
        flash('Categoria agregada correctamente', 'success')
        return redirect(url_for('categorias.index'))
    return render_template('categorias/add.html')


@categorias_bp.route('/update_categoria/<int:id>', methods=['GET', 'POST'])
def update_categoria(id):
    if request.method == 'POST':
        nombre = request.form['nombre_categoria']
        descripcion = request.form['descripcion_categoria']
        
        try:
            result = db.session.execute(
                text("""
                    UPDATE categoria_bebidas
                    SET nombre_categoria = :nombre, descripcion = :descripcion
                    WHERE id_categoria = :id;
                """), 
                {'nombre': nombre, 'descripcion': descripcion, 'id': id}
            )
            db.session.commit()
        except Exception as e:
            flash('Error al actualizar la categoria', 'error')
            return redirect(url_for('categorias.index'))
        finally:
            db.session.close()
        flash('Categoria actualizada correctamente', 'success')
        return redirect(url_for('categorias.index'))
    try:
        result = db.session.execute(
            text("""
                SELECT * FROM categoria_bebidas
                WHERE id_categoria = :id;
            """), 
            {'id': id}
        )
        categoria = result.fetchone()
    except Exception as e:
        flash('Error al obtener la categoria', 'error')
        return redirect(url_for('categorias.index'))
    finally:
        db.session.close()
    return render_template('categorias/edit.html', categoria=categoria)

@categorias_bp.route('/delete_categoria/<int:id>')
def delete_categoria(id):
    try:
        result = db.session.execute(
            text("""
                DELETE FROM categoria_bebidas
                WHERE id_categoria = :id;
            """), 
            {'id': id}
        )
        db.session.commit()
    except Exception as e:
        flash('Error al eliminar la categoria', 'error')
        return redirect(url_for('categorias.index'))
    finally:
        db.session.close()
    flash('Categoria eliminada correctamente', 'success')
    return redirect(url_for('categorias.index'))

src/templates/categorias/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Categoría</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.pag_admin_principal') }}"
            style="text-decoration: underline;">Discoteca</a>
    </nav>
    <div class="container mt-5">
        <h1 class="mb-4">Agregar Nueva Categoría</h1>
        <form action="{{ url_for('categorias.add_categoria') }}" method="POST">
            <div class="form-group">
                <label for="nombre_categoria">Nombre de la Categoría</label>
                <input type="text" class="form-control" id="nombre_categoria" name="nombre_categoria" required>
            </div>
            <div class="form-group">
                <label for="descripcion_categoria">Descripción</label>
                <textarea class="form-control" id="descripcion_categoria" name="descripcion_categoria" rows="3"
                    required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Agregar</button>
            <a href="{{ url_for('categorias.index') }}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

src/templates/categorias/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Categoría</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.pag_admin_principal') }}"
            style="text-decoration: underline;">Discoteca</a>
    </nav>
    <div class="container mt-5">
        <h1 class="mb-4">Editar Categoría</h1>
        <form action="{{ url_for('categorias.update_categoria', id=categoria[0]) }}" method="POST">
            <div class="form-group">
                <label for="nombre_categoria">Nombre de la Categoría</label>
                <input type="text" class="form-control" id="nombre_categoria" name="nombre_categoria"
                    value="{{ categoria[1] }}" required>
            </div>
            <div class="form-group">
                <label for="descripcion_categoria">Descripción</label>
                <textarea class="form-control" id="descripcion_categoria" name="descripcion_categoria" rows="3"
                    required>{{ categoria[2] }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
            <a href="{{ url_for('categorias.index') }}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

src/templates/categorias/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorías</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.pag_admin_principal') }}"
            style="text-decoration: underline;">Discoteca</a>
    </nav>
    <div class="container mt-5">
        <h1 class="mb-4">Lista de Categorías de Bebidas</h1>
        <a href="{{ url_for('categorias.add_categoria') }}" class="btn btn-success mb-3">Agregar Nueva Categoría</a>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for categoria in categorias %}
                <tr>
                    <td>{{ categoria[0] }}</td>
                    <td>{{ categoria[1] }}</td>
                    <td>{{ categoria[2] }}</td>
                    <td>
                        <a href="{{ url_for('categorias.update_categoria', id=categoria[0]) }}"
                            class="btn btn-primary btn-sm">Editar</a>
                        <a href="{{ url_for('categorias.delete_categoria', id=categoria[0]) }}"
                            class="btn btn-danger btn-sm"
                            onclick="return confirm('¿Estás seguro de que deseas eliminar este producto?');">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>